"""Add all NBA SQLAlchemy ORM models - complete migration with rank columns

Revision ID: 3236dd43e25a
Revises: 78d393826e3b
Create Date: 2025-11-20 18:39:33.130309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3236dd43e25a'
down_revision = '78d393826e3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mlb_games_away_team', table_name='mlb_games')
    op.drop_index('idx_mlb_games_date', table_name='mlb_games')
    op.drop_index('idx_mlb_games_home_team', table_name='mlb_games')
    op.drop_index('idx_mlb_games_season', table_name='mlb_games')
    op.drop_index('idx_mlb_games_status', table_name='mlb_games')
    op.drop_table('mlb_games')
    op.drop_index('idx_mlb_players_active', table_name='mlb_players')
    op.drop_index('idx_mlb_players_name', table_name='mlb_players')
    op.drop_index('idx_mlb_players_position', table_name='mlb_players')
    op.drop_index('idx_mlb_players_team_id', table_name='mlb_players')
    op.drop_table('mlb_players')
    op.drop_index('idx_mlb_teams_abbreviation', table_name='mlb_teams')
    op.drop_index('idx_mlb_teams_division', table_name='mlb_teams')
    op.drop_index('idx_mlb_teams_league', table_name='mlb_teams')
    op.drop_table('mlb_teams')
    op.alter_column('game_schedule', 'team_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('game_schedule', 'opponent_team_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('game_schedule', 'home_or_away',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.alter_column('game_schedule', 'result',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.drop_index('idx_game_schedule_date', table_name='game_schedule')
    op.drop_index('idx_game_schedule_team_result', table_name='game_schedule')
    op.drop_index('schedule_date_idx', table_name='game_schedule')
    op.drop_index('schedule_game_id_idx', table_name='game_schedule')
    op.drop_index('schedule_season_idx', table_name='game_schedule')
    op.drop_index('schedule_team_id_idx', table_name='game_schedule')
    op.alter_column('gamelogs', 'points',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gamelogs', 'assists',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gamelogs', 'rebounds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gamelogs', 'steals',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gamelogs', 'blocks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gamelogs', 'turnovers',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gamelogs', 'minutes_played',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_gamelogs_points', table_name='gamelogs')
    op.create_index('idx_gamelogs_points', 'gamelogs', ['points'], unique=False)
    op.create_foreign_key(None, 'gamelogs', 'teams', ['team_id'], ['team_id'])
    op.alter_column('league_dash_team_stats', 'team_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('team_dash_composite_idx', table_name='league_dash_team_stats')
    op.drop_index('team_dash_season_idx', table_name='league_dash_team_stats')
    op.drop_index('idx_leaguedash_fantasy', table_name='leaguedashplayerstats')
    op.drop_index('idx_leaguedash_points', table_name='leaguedashplayerstats')
    op.drop_index('idx_leaguedash_season', table_name='leaguedashplayerstats')
    op.drop_index('leaguedash_player_season_idx', table_name='leaguedashplayerstats')
    op.drop_index('leaguedash_season_idx', table_name='leaguedashplayerstats')
    op.drop_index('leaguedash_team_idx', table_name='leaguedashplayerstats')
    op.create_index('idx_leaguedashplayerstats_player_id', 'leaguedashplayerstats', ['player_id'], unique=False)
    op.create_index('idx_leaguedashplayerstats_season', 'leaguedashplayerstats', ['season'], unique=False)
    op.create_index('idx_leaguedashplayerstats_team_id', 'leaguedashplayerstats', ['team_id'], unique=False)
    op.alter_column('player_streaks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index('streaks_player_stat_idx', table_name='player_streaks')
    op.drop_index('streaks_season_idx', table_name='player_streaks')
    op.alter_column('player_z_scores', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('unique_player_id', 'player_z_scores', type_='unique')
    op.create_index('idx_player_z_scores_player_id', 'player_z_scores', ['player_id'], unique=False)
    op.create_foreign_key(None, 'player_z_scores', 'players', ['player_id'], ['player_id'], ondelete='CASCADE')
    op.drop_column('player_z_scores', 'ft_pct')
    op.drop_column('player_z_scores', 'ast')
    op.drop_column('player_z_scores', 'fg_pct')
    op.drop_column('player_z_scores', 'fg3m')
    op.drop_column('player_z_scores', 'reb')
    op.drop_column('player_z_scores', 'blk')
    op.drop_column('player_z_scores', 'dd2')
    op.drop_column('player_z_scores', 'fg3_pct')
    op.drop_column('player_z_scores', 'tov')
    op.drop_column('player_z_scores', 'stl')
    op.drop_column('player_z_scores', 'pts')
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('players', 'born_date',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='born_date::date')
    op.alter_column('statistics', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistics', 'season_year',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_constraint('unique_player_season', 'statistics', type_='unique')
    op.drop_index('idx_statistics_assists', table_name='statistics')
    op.create_index('idx_statistics_assists', 'statistics', ['assists'], unique=False)
    op.drop_index('idx_statistics_player_season_year', table_name='statistics')
    op.create_index('idx_statistics_player_season_year', 'statistics', ['player_id', 'season_year'], unique=False)
    op.drop_index('idx_statistics_points', table_name='statistics')
    op.create_index('idx_statistics_points', 'statistics', ['points'], unique=False)
    op.drop_index('idx_statistics_rebounds', table_name='statistics')
    op.create_index('idx_statistics_rebounds', 'statistics', ['rebounds'], unique=False)
    op.alter_column('team_game_stats', 'team_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('team_game_stats', 'opponent_team_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('team_game_stats', 'game_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('idx_team_game_stats_date', table_name='team_game_stats')
    op.drop_index('idx_team_game_stats_game', table_name='team_game_stats')
    op.drop_index('idx_team_game_stats_points', table_name='team_game_stats')
    op.drop_index('idx_team_game_stats_team_game', table_name='team_game_stats')
    op.drop_index('team_stats_date_idx', table_name='team_game_stats')
    op.drop_index('team_stats_game_team_idx', table_name='team_game_stats')
    op.drop_index('team_stats_season_idx', table_name='team_game_stats')
    op.create_index('idx_team_game_stats_game_date', 'team_game_stats', ['game_date'], unique=False)
    op.create_index('idx_team_game_stats_team_id', 'team_game_stats', ['team_id'], unique=False)
    op.drop_constraint('team_game_stats_game_id_team_id_fkey', 'team_game_stats', type_='foreignkey')
    op.create_foreign_key(None, 'team_game_stats', 'teams', ['team_id'], ['team_id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'team_game_stats', type_='foreignkey')
    op.create_foreign_key('team_game_stats_game_id_team_id_fkey', 'team_game_stats', 'game_schedule', ['game_id', 'team_id'], ['game_id', 'team_id'], ondelete='CASCADE')
    op.drop_index('idx_team_game_stats_team_id', table_name='team_game_stats')
    op.drop_index('idx_team_game_stats_game_date', table_name='team_game_stats')
    op.create_index('team_stats_season_idx', 'team_game_stats', ['season'], unique=False)
    op.create_index('team_stats_game_team_idx', 'team_game_stats', ['game_id', 'team_id'], unique=False)
    op.create_index('team_stats_date_idx', 'team_game_stats', ['game_date'], unique=False)
    op.create_index('idx_team_game_stats_team_game', 'team_game_stats', ['team_id', 'game_id'], unique=False)
    op.create_index('idx_team_game_stats_points', 'team_game_stats', [sa.text('pts DESC')], unique=False)
    op.create_index('idx_team_game_stats_game', 'team_game_stats', ['game_id'], unique=False)
    op.create_index('idx_team_game_stats_date', 'team_game_stats', ['game_date'], unique=False)
    op.alter_column('team_game_stats', 'game_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('team_game_stats', 'opponent_team_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('team_game_stats', 'team_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index('idx_statistics_rebounds', table_name='statistics')
    op.create_index('idx_statistics_rebounds', 'statistics', [sa.text('rebounds DESC')], unique=False)
    op.drop_index('idx_statistics_points', table_name='statistics')
    op.create_index('idx_statistics_points', 'statistics', [sa.text('points DESC')], unique=False)
    op.drop_index('idx_statistics_player_season_year', table_name='statistics')
    op.create_index('idx_statistics_player_season_year', 'statistics', ['player_id', 'season_year'], unique=True)
    op.drop_index('idx_statistics_assists', table_name='statistics')
    op.create_index('idx_statistics_assists', 'statistics', [sa.text('assists DESC')], unique=False)
    op.create_unique_constraint('unique_player_season', 'statistics', ['player_id', 'season_year'])
    op.alter_column('statistics', 'season_year',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('statistics', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'born_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('player_z_scores', sa.Column('pts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('stl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('tov', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('fg3_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('dd2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('blk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('reb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('fg3m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('fg_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('ast', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('player_z_scores', sa.Column('ft_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player_z_scores', type_='foreignkey')
    op.drop_index('idx_player_z_scores_player_id', table_name='player_z_scores')
    op.create_unique_constraint('unique_player_id', 'player_z_scores', ['player_id'])
    op.alter_column('player_z_scores', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('streaks_season_idx', 'player_streaks', ['season'], unique=False)
    op.create_index('streaks_player_stat_idx', 'player_streaks', ['player_id', 'stat', 'season'], unique=False)
    op.alter_column('player_streaks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.drop_index('idx_leaguedashplayerstats_team_id', table_name='leaguedashplayerstats')
    op.drop_index('idx_leaguedashplayerstats_season', table_name='leaguedashplayerstats')
    op.drop_index('idx_leaguedashplayerstats_player_id', table_name='leaguedashplayerstats')
    op.create_index('leaguedash_team_idx', 'leaguedashplayerstats', ['team_id'], unique=False)
    op.create_index('leaguedash_season_idx', 'leaguedashplayerstats', ['season'], unique=False)
    op.create_index('leaguedash_player_season_idx', 'leaguedashplayerstats', ['player_id', 'season'], unique=False)
    op.create_index('idx_leaguedash_season', 'leaguedashplayerstats', ['season'], unique=False)
    op.create_index('idx_leaguedash_points', 'leaguedashplayerstats', [sa.text('pts DESC')], unique=False)
    op.create_index('idx_leaguedash_fantasy', 'leaguedashplayerstats', [sa.text('nba_fantasy_pts DESC')], unique=False)
    op.create_index('team_dash_season_idx', 'league_dash_team_stats', ['season'], unique=False)
    op.create_index('team_dash_composite_idx', 'league_dash_team_stats', ['team_id', 'season', 'season_type'], unique=False)
    op.alter_column('league_dash_team_stats', 'team_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'gamelogs', type_='foreignkey')
    op.drop_index('idx_gamelogs_points', table_name='gamelogs')
    op.create_index('idx_gamelogs_points', 'gamelogs', [sa.text('points DESC')], unique=False)
    op.alter_column('gamelogs', 'minutes_played',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'00:00'::character varying"),
               existing_nullable=True)
    op.alter_column('gamelogs', 'turnovers',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('gamelogs', 'blocks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('gamelogs', 'steals',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('gamelogs', 'rebounds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('gamelogs', 'assists',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('gamelogs', 'points',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_index('schedule_team_id_idx', 'game_schedule', ['team_id'], unique=False)
    op.create_index('schedule_season_idx', 'game_schedule', ['season'], unique=False)
    op.create_index('schedule_game_id_idx', 'game_schedule', ['game_id'], unique=False)
    op.create_index('schedule_date_idx', 'game_schedule', ['game_date'], unique=False)
    op.create_index('idx_game_schedule_team_result', 'game_schedule', ['team_id', 'result'], unique=False)
    op.create_index('idx_game_schedule_date', 'game_schedule', ['game_date'], unique=False)
    op.alter_column('game_schedule', 'result',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('game_schedule', 'home_or_away',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.alter_column('game_schedule', 'opponent_team_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('game_schedule', 'team_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table('mlb_teams',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('league', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('venue_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("league::text = ANY (ARRAY['AL'::character varying, 'NL'::character varying, 'American League'::character varying, 'National League'::character varying]::text[])", name='mlb_teams_league_check'),
    sa.PrimaryKeyConstraint('team_id', name='mlb_teams_pkey'),
    sa.UniqueConstraint('abbreviation', name='mlb_teams_abbreviation_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_mlb_teams_league', 'mlb_teams', ['league'], unique=False)
    op.create_index('idx_mlb_teams_division', 'mlb_teams', ['division'], unique=False)
    op.create_index('idx_mlb_teams_abbreviation', 'mlb_teams', ['abbreviation'], unique=False)
    op.create_table('mlb_players',
    sa.Column('player_id', sa.INTEGER(), server_default=sa.text("nextval('mlb_players_player_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bats', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('throws', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('debut_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("bats = ANY (ARRAY['L'::bpchar, 'R'::bpchar, 'S'::bpchar])", name='mlb_players_bats_check'),
    sa.CheckConstraint("throws = ANY (ARRAY['L'::bpchar, 'R'::bpchar])", name='mlb_players_throws_check'),
    sa.ForeignKeyConstraint(['team_id'], ['mlb_teams.team_id'], name='mlb_players_team_id_fkey'),
    sa.PrimaryKeyConstraint('player_id', name='mlb_players_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_mlb_players_team_id', 'mlb_players', ['team_id'], unique=False)
    op.create_index('idx_mlb_players_position', 'mlb_players', ['position'], unique=False)
    op.create_index('idx_mlb_players_name', 'mlb_players', ['name'], unique=False)
    op.create_index('idx_mlb_players_active', 'mlb_players', ['is_active'], unique=False)
    op.create_table('mlb_games',
    sa.Column('game_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('game_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('probable_pitcher_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probable_pitcher_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=True),
    sa.Column('weather_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weather_wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weather_wind_direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['mlb_teams.team_id'], name='mlb_games_away_team_id_fkey'),
    sa.ForeignKeyConstraint(['home_team_id'], ['mlb_teams.team_id'], name='mlb_games_home_team_id_fkey'),
    sa.ForeignKeyConstraint(['probable_pitcher_away'], ['mlb_players.player_id'], name='mlb_games_probable_pitcher_away_fkey'),
    sa.ForeignKeyConstraint(['probable_pitcher_home'], ['mlb_players.player_id'], name='mlb_games_probable_pitcher_home_fkey'),
    sa.PrimaryKeyConstraint('game_id', name='mlb_games_pkey')
    )
    op.create_index('idx_mlb_games_status', 'mlb_games', ['status'], unique=False)
    op.create_index('idx_mlb_games_season', 'mlb_games', ['season'], unique=False)
    op.create_index('idx_mlb_games_home_team', 'mlb_games', ['home_team_id'], unique=False)
    op.create_index('idx_mlb_games_date', 'mlb_games', ['game_date'], unique=False)
    op.create_index('idx_mlb_games_away_team', 'mlb_games', ['away_team_id'], unique=False)
    # ### end Alembic commands ###

